### ISSUE TITLE
Cannot visualize complete model in Gazebo

### ISSUE THREAD

**Issue by aPonza** [frankaemika/franka_ros#28] opened 2018-09-03 14:03 UTC
This is very possibly a duplicate of [this issue](https://github.com/frankaemika/franka_ros/issues/12), and feel free to close/merge it if that is the case.

I am trying to visualize the robot in Gazebo, but I am only getting the base of the robot, whereas with RViz I can see the whole thing. I'm attaching [both MWEs](https://github.com/frankaemika/franka_ros/files/2345791/foo.zip) (put in a catkin workspace and it should work, it's an empty package apart from the launch files, the urdf and config stuff), which I am launching with `$ roslaunch foo gazebo.launch` and `$ roslaunch foo display.launch`.

In RViz the whole arm is visible on top of the box, whereas in Gazebo only the box and robot base (first link basically) are visible (and it floats, sometimes...).

**Comment by fwalch** [comment] 2018-09-04 14:06
Gazebo [requires](http://gazebosim.org/tutorials?tut=ros_urdf#Required) inertial tags, and if these are removed from the `base_link` in your example, not even the box is shown anymore. So yes, it seems like this is a duplicate of #12.

**Closed as completed by fwalch** 2018-09-04 14:06 UTC
