### ISSUE TITLE
franka_control.launch result in end-effector not connected

### ISSUE THREAD

**Issue by Jekyll1021** [frankaemika/franka_ros#118] opened 2020-10-15 23:12 UTC
If I run gripper grasp app from DESK, the task is completed properly. However, after I run `roslaunch franka_control franka_control.launch load_gripper:=true robot_ip:=172.16.0.2`, DESK showed "end-effector not connected" in Robot Status, and any request through franka_gripper/move or franka_gripper/grasp received a fail signal (although yield correct behavior) as a result. 

Where should I start debugging this problem?

**Comment by sgabl** [comment] 2020-10-21 13:30
Hi, during the time you're connected to the FCI it's fine that DESK shows "end-effector not connected". However, the gripper move should not fail when the correct parameter are used. You could test if [the libfranka grasp example](https://github.com/frankaemika/libfranka/blob/master/examples/grasp_object.cpp) works.

**Comment by bibbygoodwin** [comment] 2021-05-27 17:43
Hi @sgabl , I'm also having this problem - with interface v4.0.4 and the latest libraries: libfranka 0.8.0 and franka_ros 0.7.1.

As soon as I run `roslaunch franka_control franka_control.launch`, the web interface says "End effector not connected". When subsequently trying to send commands through franka_ros, for example with `panda_moveit_config`, planning is unsuccessful in this state.

It might be true that pure libfranka control still works (though I find that in this state I'm also not able to run the Desk demos) but in any case, if ROS doesn't work in this state, it makes the robot very hard to work with.

**Comment by MadBot97** [comment] 2021-08-10 12:31
Hi @sgabl and @bibbygoodwin, I had the same issue. Have you been able to manage it? Thanks.

**Comment by matteolucchi** [comment] 2021-09-28 11:58
Hi, I am also facing this problem with libfranka 0.8.0 and franka_ros 0.7.1 . Does anyone have any leads on how to solve this?

**Comment by MadBot97** [comment] 2021-09-28 12:13
Hi @matteolucchi, at the end I solved the problem by installing libfranka 0.7.1 and franka_ros 0.7.0. Be sure when you unblock joints from franka desk that also the gripper moves (otherwise you need to activate the gripper connection in the settings of franka desk). Hope this can help you!

**Comment by gollth** [comment] 2022-01-03 16:00
Hi all,

to amend a bit to @sgabl 's answer:

> "End effector not connected"

This warning is "expected behavior" since you can only control the robot *either* via FCI *or* via Desk. See the "switch" before the "robot control" block in [this graphic](https://github.com/frankaemika/the_reference_platform/blob/main/fig/overview_system_architecture.png) for more details. Regardless of the warning in Desk, it should be possible to control the gripper via ROS actions or libfranka commands (like it seems to be the case for you @Jekyll1021).

That action calls return errors can have different reasons. The most likely one is, that your goal width and tolerances are too narrow. Note that when using `franka_gripper/grasp` (or `franka_gripper/gripper_command` for that matter) the fingers will _always_ close (or open) fully until they feel resistance. Only then the current finger width is checked against the one you provided as goal. If it lies within the lower & upper bounds you provided, the action succeeds. Refer also to [the documentation](https://frankaemika.github.io/docs/franka_ros.html#franka-gripper) about this.

Lastly the gripper must be able to know where its hard limits are, which it does by homing its fingers inside the carriage. This is usually done when you unlock the brakes. Alternatively you can call the `franka_gripper/homing` action manually. This implies that you have setup a Franka Hand in the Settings Panel of Desk:

![Screenshot from 2022-01-03 16-48-32](https://user-images.githubusercontent.com/31999281/147951006-455faa8a-83b2-4c0b-bc6e-0deed3a1f42b.png)

Let us know if this helps @Jekyll1021

**Comment by maxiuw** [comment] 2022-09-17 15:02
I followed the last step posted by  @gollthm. It did work however, main problem seem to be the gripper being 'open too much'. Fixed by manually closing the gripper and applying 'homing'

**Closed as completed** 2022-09-19 06:45 UTC
